Upgrade edge
UKCloud/documentation pull request #1109
Opened 2020-09-15 13:07 UTC by suehighmoor

2020-09-15 13:51 UTC, SteveHallUKCLoud approved these changes
LGTM!

2020-09-17 15:04 UTC, mikepukcloud requested changes
vApp network description should include static routing e.g. If you've configured a vApp network to use either NAT, firewall or static route functionality, an NSX edge services gateway is required.

and 

in the section "An edge will be present on your vApp network if the network is:" only DHCP is listed this should also include NAT,Firewall and Static Route if we are listing services here too.

2020-09-17 15:18 UTC, suehighmoor commented
@sde1aney, could you just confirm which way to go here regarding @mikepukcloud's comment. We mention NAT and firewall in as being the reason for having an edge gateway in the description of a vApp network at the beginning of the article (with no mention of DHCP), but we list DHCP as being one of the reasons later on. We should be consistent here.

2020-09-18 14:17 UTC, mikepukcloud approved these changes

2020-09-18 14:20 UTC, merged