Converting azurerm module to az module
UKCloud/documentation pull request #1221
Opened 2020-11-25 13:32 UTC by ReissJJarvis05

Converted all code in the guides to use the new Az module instead of the old AzureRm module.

2020-12-01 11:40 UTC, wturner123 requested changes
Majority of changes are good, but some recurring things across multiple files that need fixing.

2020-12-01 11:40 UTC, wturner123 commented on articles/azure/azs-how-move-vm-new-vnet-ps.md
> +  }
```suggestion
}
else {
    $ManagedDisks = $false
}
```

2020-12-01 11:40 UTC, wturner123 commented on articles/azure/azs-how-move-vm-new-vnet-ps.md
> +$NewNic = New-AzNetworkInterface -Name $NewNicName -ResourceGroupName $NewVNet.ResourceGroupName -Location $NewVNet.Location -IpConfiguration $NewIpConfig -NetworkSecurityGroupId $Nic.NetworkSecurity
What happened with the PrivateIpAddress param?
` -PrivateIpAddress $NewPrivateIp`

2020-12-02 10:04 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-operators.md
> +Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
Think we need to break this up like below. Also reword the comment about the TLS command.
```
# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Install the Az.BootStrapper module
Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
```

2020-12-02 10:05 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-users.md
> +Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
Think we need to break this up like below. Also reword the comment about the TLS command.
```
# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Install the Az.BootStrapper module
Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
```

2020-12-02 10:06 UTC, wturner123 commented on articles/azure/azs-how-deploy-sql-template-powershell.md
> +    }
```suggestion
    }
```
Cleaning up white space.

2020-12-02 10:08 UTC, wturner123 commented on articles/azure/azs-how-move-vm-new-vnet-ps.md
> +$NewNic = New-AzNetworkInterface -Name $NewNicName -ResourceGroupName $NewVNet.ResourceGroupName -Location $NewVNet.Location -IpConfiguration $NewIpConfig -NetworkSecurityGroupId $Nic.NetworkSecurity
@ReissJJarvis05 Was there a specific reason why this was removed?

2020-12-02 10:09 UTC, wturner123 requested changes
Just a couple more things to go through.

2020-12-02 13:27 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-operators.md
> +# On some systems, you may need to run this command to be able to connect to PowerShell Gallery
```suggestion
# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```
Missing the comment change.

2020-12-02 13:27 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-users.md
> +# On some systems, you may need to run this command to be able to connect to PowerShell Gallery
```suggestion
# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```
Missing the comment change.

2020-12-02 14:12 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-operators.md
> +# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```suggestion
# On some older systems, you may need to explicitly set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```
I can't spell...

2020-12-02 14:12 UTC, wturner123 commented on articles/azure/azs-how-configure-powershell-users.md
> +# On some older systems, you may need to explicity set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```suggestion
# On some older systems, you may need to explicitly set the TLS 1.2 security protocol to be able to interact with PowerShell Gallery
```
I can't spell...

2021-01-06 17:16 UTC, wturner123 commented on articles/azure/azs-how-convert-to-managed-disks-ps.md
> -
Need to check whether this is still a valid statement for the Az command.

2021-01-06 17:42 UTC, wturner123 commented on articles/azure/azs-how-configure-custom-script-extension.md
> +Set-AzVMExtension -ResourceGroupName $RGName -Location $Location -VMName $VMName -Name $Extensions[0].Type -Publisher $Extensions[0].PublisherName -ExtensionType $Extensions[0].Type -TypeHandlerVersi
Needs looking into, not sure if this is correct.

2021-01-06 17:42 UTC, wturner123 commented on articles/azure/azs-how-configure-custom-script-extension.md
> +Set-AzVMExtension -ResourceGroupName $RGName -Location $Location -VMName $VMName -Name $Extensions[0].Type -Publisher $Extensions[0].PublisherName -ExtensionType $Extensions[0].Type -TypeHandlerVersi
Needs looking into, not sure if this is correct.

2021-01-07 10:20 UTC, wturner123 approved these changes
LGTM.
Reviewed all articles and double-checked for any remaning -Azure or -AzureRM commands.

2021-01-07 11:39 UTC, cblackuk approved these changes
LGTM

2021-01-07 11:58 UTC, suehighmoor approved these changes
LGTM

2021-01-07 11:58 UTC, merged