Update enbl-sco-capscpa.md
UKCloud/documentation pull request #1266
Opened 2020-12-08 12:30 UTC by bartchal

changed based on experience with customers

2020-12-10 13:38 UTC, NickStobbart requested changes
This line should change:
Cloud Enablement sizing | one bay = 10U, 1kW per month
to
Cloud Enablement sizing | one bay = 10U, 1kW of power

kW is not a measure measurement of power usage over time. That would be kW/h's

2020-12-10 15:30 UTC, SteveHallUKCLoud approved these changes
LGTM

2020-12-10 17:05 UTC, suehighmoor approved these changes
LGTM

2021-01-11 15:43 UTC, NickStobbart approved these changes

2021-01-11 15:48 UTC, merged