Patch status update
UKCloud/documentation pull request #1628
Opened 2021-03-03 16:10 UTC by stevedicko

Added new standard text at the top of all Service Scopes stating about required patch health.
Added section to monitoring FAQ with regards to the use of an agent.

2021-03-04 07:55 UTC, SteveHallUKCLoud requested changes

2021-03-04 07:55 UTC, SteveHallUKCLoud commented on articles/managed-services/man-monitoring-faq.md
> +## Do I need to instal an agent within my VM to enable this service?
typo - Install

2021-03-05 10:29 UTC, suehighmoor approved these changes
LGTM

2021-03-05 10:29 UTC, suehighmoor commented on articles/managed-services/man-monitoring-faq.md
> +## Do I need to instal an agent within my VM to enable this service?
Fixed!

2021-03-05 10:46 UTC, SteveHallUKCLoud approved these changes
LGTM

2021-03-05 10:50 UTC, merged